### ISSUE TITLE
似乎内存回收有问题？

### ISSUE THREAD

**Issue by evolighting** [Senorsen/netease-cloud-music-rpm#1]
我在linuxtoy上看到，就试了一下；

首先凡是和chrome有关的软件都会出现的字体问题，但是幸好这个有字体设置；

然后，一旦开始放歌，内存占用就会线性增加直到占满全部内存....
不知道是不是我个人的问题？

**Comment by XuShaohua** [comment]
请尝试临时修复.
https://bbs.deepin.org/forum.php?mod=viewthread&tid=39708

**Comment by Senorsen** [comment]
感谢楼上回复，过会儿我在rpm包里应用一下这个fix~

**Comment by XuShaohua** [comment]
@Senorsen 建议直接把/usr/bin/netease-cloud-music 这个软链接换成下在这个脚本文件, 

[netease-cloud-music.tar.gz](https://github.com/Senorsen/netease-cloud-music-rpm/files/283745/netease-cloud-music.tar.gz)

论坛里的那个补丁最后生成的就是这个shell脚本

**Comment by Senorsen** [comment]
@xushaohua 对，我就是打算这样做的 ~

**Comment by XuShaohua** [comment]
+1

**Comment by evolighting** [comment]
@XuShaohua @Senorsen 感谢修复！

**Comment by XuShaohua** [comment]
@Senorsen 
这个shell脚本有个bug, 需要把
`/usr/lib/netease-cloud-music/netease-cloud-music`
改成
`/usr/lib/netease-cloud-music/netease-cloud-music $*`
这样才能把传过来的参数传给可执行文件, 不然的话, 就无法在文件管理器里面双击mp3文件用云音乐来播放了

**Comment by Senorsen** [comment]
@XuShaohua 谢谢提醒！

**Comment by XuShaohua** [comment]
客气.
