### ISSUE TITLE
打开后播放音乐将会导致gnome shell崩溃

### ISSUE THREAD

**Issue by evolighting** [Senorsen/netease-cloud-music-rpm#11]
崩溃后自动注销.....这样不知道如何获得崩溃信息呢？

升级24和网易云音乐后才遇到这个问题...

fedora桌面用户非专业人员请谅解

**Comment by Senorsen** [comment]
Hi, 由于我也不是官方开发者，只能给你一点微小的建议；

在 terminal 中输入：

```
netease-cloud-music >~/netease-cloud-music.log 2>~/netease-cloud-music.err
```

**Comment by evolighting** [comment]
[0711/215755:ERROR:edid_parser.cc(192)] invalid EDID: human unreadable char in name
[0711/215827:ERROR:edid_parser.cc(192)] invalid EDID: human unreadable char in name
ICE default IO error handler doing an exit(), pid = 12980, errno = 11
[0711/215834:ERROR:x11_util.cc(82)] X IO error received (X server probably went away)

只有err有这样的错误，看起来就是gnome挂掉了？依旧毫无头绪，感谢提供指导....
但是依旧没什么用...
翻journalctl大概看到这样的结果.....
Process 12980 (netease-cloud-music) of user 1000 killed by SIGSEGV - dumping core
Process 6292 (gnome-shell) of user 1000 killed by SIGABRT - dumping core
Unrecoverable failure in required component org.gnome.Shell.desktop

**Comment by evolighting** [comment]
对了上游可以往哪里反映呢？
不过fedora似乎也不是官方支持的呢....

**Comment by Senorsen** [comment]
可以试着到 deepin 论坛反馈下~

**Comment by Senorsen** [comment]
Hi, 此 repo 停止维护了。请你使用 FZUG 的网易云音乐软件包。
