### ISSUE TITLE
Fedora25窗口拖动问题

### ISSUE THREAD

**Issue by raojinlin** [Senorsen/netease-cloud-music-rpm#13]
窗口拖动全靠运气....排版也有混乱,点击一个栏目后别的栏目有那么一两个不能切换(点击),
系统版本:Fedora25 64bit
软件版本:1.0.0(Build 1026)

![selection_007](https://cloud.githubusercontent.com/assets/19492031/20858708/7d632748-b986-11e6-9df2-0973cb00693c.png)

**Comment by raojinlin** [comment]
忘了一点:切换窗口的时候点击顶部还是可以拖动的,貌似只有这个时候可以

**Comment by Johnliu520** [comment]
我也是25安装后无法播放音乐，怎么回事啊？可以播放mv。

**Comment by Senorsen** [comment]
Hi, 此 repo 停止维护了。请你使用 FZUG 的网易云音乐软件包。
