### ISSUE TITLE
Fdora 25 每次退出应用都会提示崩溃

### ISSUE THREAD

**Issue by S3CR3T-M3N0N** [Senorsen/netease-cloud-music-rpm#15]
如图所未，每次退出应用的时候都会提示程序崩溃。
![2017-01-23 05-30-58](https://cloud.githubusercontent.com/assets/3233275/22186237/6ffed312-e12d-11e6-94c7-48168208d1c0.png)

我的系统环境
![screenshot-20170101045625-734x518](https://cloud.githubusercontent.com/assets/3233275/22186242/9b40c60c-e12d-11e6-9d91-4340217e589b.png)

**Comment by Senorsen** [comment]
Hi, 此 repo 停止维护了。请你使用 FZUG 的网易云音乐软件包。
