### ISSUE TITLE
problem with netease downloading

### ISSUE THREAD

**Issue by Kitein** [Senorsen/netease-cloud-music-rpm#19]
![screenshot from 2017-05-07 15-08-27](https://cloud.githubusercontent.com/assets/28451961/25781224/52f3cd34-3337-11e7-81b0-0464b3ca2462.png)

**Comment by Kitein** [comment]
can u tell me how to solve the problem as i use fedora 25

**Comment by Senorsen** [comment]
CDN 缓存问题，现已解决。

**Comment by Kitein** [comment]
感谢,感谢

⁣Gesendet mit BlueMail ​
