### ISSUE TITLE
怎么回事？

### ISSUE THREAD

**Issue by houbaron** [Senorsen/netease-cloud-music-rpm#2]
Failed to open: /var/cache/dnf/x86_64/7/x86_64/7/epel/repodata/972e41b17d3c9b7f131601a7df10352ac1b67853fe261cabec0bd5a35dca5302-updateinfo.xml.bz2.

**Comment by Senorsen** [comment]
Try:

```
rm -rf /var/cache/dnf/*
```

**Comment by Senorsen** [comment]
或者试试 yum

**Comment by houbaron** [comment]
用yum怎么安？

**Comment by Senorsen** [comment]
把`dnf`替换为`yum`就好了吧

**Comment by houbaron** [comment]
因为依赖关系问题而跳过的软件包：
    netease-cloud-music-0.9.0-4.x86_64 来自 senorsen
    openal-soft-1.16.0-3.el7.x86_64 来自 epel
    qt5-qtdeclarative-5.6.0-3.el7.x86_64 来自 epel
    qt5-qtmultimedia-5.6.0-3.el7.x86_64 来自 epel
    qt5-qtx11extras-5.6.0-3.el7.x86_64 来自 epel
    qt5-qtxmlpatterns-5.6.0-4.el7.x86_64 来自 epel

**Comment by houbaron** [comment]
这些包应该怎么安装呢

**Comment by Senorsen** [comment]
那应该是依赖不满足吧，试着安装一下rpmfusion？

**Comment by Senorsen** [comment]
Hi, 验证了一下，因为依赖的问题，云音乐很难在 CentOS 7 下运行

**Comment by houbaron** [comment]
确实，已经转投ubuntu
