### ISSUE TITLE
fedora 26 安装时校验失败

### ISSUE THREAD

**Issue by nyms7** [Senorsen/netease-cloud-music-rpm#20]
[MIRROR] netease-cloud-music-1.0.0-1.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 979f86721c22af6519561e9f16f071add19b9e86(sha1)  Expected: 74251c275d8f97f89fd699453a6bd1969583b66a(sha1)

**Comment by c4yg70** [comment]
same, with fedora 26 all ostree involved

**Comment by Senorsen** [comment]
https://dl.senorsen.com/pub/package/linux/rpm/

**Comment by Senorsen** [comment]
Solved
