### ISSUE TITLE
openSUSE Leap 42.1 无法安装

### ISSUE THREAD

**Issue by zmj1316** [Senorsen/netease-cloud-music-rpm#6]
看来依赖差的有点远...

**Comment by zmj1316** [comment]
播放音乐时崩溃
symbol lookup error: /lib64/libssl.so.1.0.0: undefined symbol: OPENSSL_init_library

**Comment by Senorsen** [comment]
你的openssl版本是？

**Comment by zmj1316** [comment]
@Senorsen 1.0.1i-15.1-x86_64 升级自1.0.1i-9.1-x86_64 都不行

**Comment by zmj1316** [comment]
用alien转了变成  segmentation fault 了...

**Comment by zmj1316** [comment]
追了一下发现是在 libkdecore.so.5 看来是没戏了
