### ISSUE TITLE
Fail on fedora 22

### ISSUE THREAD

**Issue by Jerry-Ma** [Senorsen/netease-cloud-music-rpm#7]
Hi,

I tried install it under fedora 22 but it gives the following error:

Error: nothing provides gstreamer1-plugins-ugly(x86-32) needed by netease-cloud-music-0.9.0-3.i686
(try to add '--allowerasing' to command line to replace conflicting packages)

**Comment by Senorsen** [comment]
Hi, there are a few dependencies problem under fedora 22. It could only be run on fedora 23+.
