### ISSUE TITLE
Fedora 23 checksum doesn't match

### ISSUE THREAD

**Issue by Yienschwen** [Senorsen/netease-cloud-music-rpm#8]
Arch: x86_64
dnf claims:
[MIRROR] netease-cloud-music-0.9.0-4.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 32986e4c9b93a09793b3744a40d6937c4104d23b(sha1)  Expected: 60625250fdaa211d1fdaecba98ee6a72d55b2355(sha1)

**Comment by Senorsen** [comment]
Hi, 如果问题持续，可先通过执行：

```
sudo dnf install http://dl-http.senorsen.com/pub/package/linux/rpm/netease-cloud-music-0.9.0-4.x86_64.rpm
```

安装
