### ISSUE TITLE
fedora 24 下 libcue 包依赖问题

### ISSUE THREAD

**Issue by choleraehyq** [Senorsen/netease-cloud-music-rpm#9]
升级到 fedora 24 之后从你的源安装网易云音乐，运行报错找不到 libcue.so.1 ，我看了一下根据依赖自动安装的是 libcue.x86_64-2.0.1-2.fc24 ，后来我自己编译安装了 libcue 1.4.0 就可以运行了。

**Comment by Senorsen** [comment]
谢谢提醒，将在近期尝试解决一下

**Comment by Senorsen** [comment]
Hi, 我全新安装的 Fedora 24 没有这个问题~ 测试使用的是 netease-cloud-music-1.0.0-1

**Comment by Senorsen** [comment]
Hi, 此 repo 停止维护了。请你使用 FZUG 的网易云音乐软件包。
